"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _DownloadPhase:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DownloadPhaseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DownloadPhase.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DOWNLOAD_PHASE_UNSPECIFIED: _DownloadPhase.ValueType  # 0
    DOWNLOAD_PHASE_DOWNLOADING: _DownloadPhase.ValueType  # 1
    DOWNLOAD_PHASE_VERIFYING: _DownloadPhase.ValueType  # 2
    DOWNLOAD_PHASE_FINALIZING: _DownloadPhase.ValueType  # 3

class DownloadPhase(_DownloadPhase, metaclass=_DownloadPhaseEnumTypeWrapper): ...

DOWNLOAD_PHASE_UNSPECIFIED: DownloadPhase.ValueType  # 0
DOWNLOAD_PHASE_DOWNLOADING: DownloadPhase.ValueType  # 1
DOWNLOAD_PHASE_VERIFYING: DownloadPhase.ValueType  # 2
DOWNLOAD_PHASE_FINALIZING: DownloadPhase.ValueType  # 3
Global___DownloadPhase: _TypeAlias = DownloadPhase  # noqa: Y015

class _SampleFormat:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SampleFormatEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SampleFormat.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNSPECIFIED: _SampleFormat.ValueType  # 0
    S16LE: _SampleFormat.ValueType  # 1

class SampleFormat(_SampleFormat, metaclass=_SampleFormatEnumTypeWrapper): ...

UNSPECIFIED: SampleFormat.ValueType  # 0
S16LE: SampleFormat.ValueType  # 1
Global___SampleFormat: _TypeAlias = SampleFormat  # noqa: Y015

@_typing.final
class ProtocolVersion(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAJOR_FIELD_NUMBER: _builtins.int
    MINOR_FIELD_NUMBER: _builtins.int
    major: _builtins.int
    minor: _builtins.int
    def __init__(
        self,
        *,
        major: _builtins.int = ...,
        minor: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["major", b"major", "minor", b"minor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProtocolVersion: _TypeAlias = ProtocolVersion  # noqa: Y015

@_typing.final
class Capability(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    SUPPORTED_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    supported: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        supported: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "supported", b"supported"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Capability: _TypeAlias = Capability  # noqa: Y015

@_typing.final
class DescribeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DescribeRequest: _TypeAlias = DescribeRequest  # noqa: Y015

@_typing.final
class DescribeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROTOCOL_FIELD_NUMBER: _builtins.int
    ENGINE_ID_FIELD_NUMBER: _builtins.int
    ENGINE_VERSION_FIELD_NUMBER: _builtins.int
    CAPABILITIES_FIELD_NUMBER: _builtins.int
    MAX_CONCURRENCY_FIELD_NUMBER: _builtins.int
    ALIGNMENT_FIELD_NUMBER: _builtins.int
    engine_id: _builtins.str
    engine_version: _builtins.str
    max_concurrency: _builtins.int
    @_builtins.property
    def protocol(self) -> Global___ProtocolVersion: ...
    @_builtins.property
    def capabilities(self) -> _containers.RepeatedCompositeFieldContainer[Global___Capability]: ...
    @_builtins.property
    def alignment(self) -> Global___AlignmentCapability: ...
    def __init__(
        self,
        *,
        protocol: Global___ProtocolVersion | None = ...,
        engine_id: _builtins.str = ...,
        engine_version: _builtins.str = ...,
        capabilities: _abc.Iterable[Global___Capability] | None = ...,
        max_concurrency: _builtins.int = ...,
        alignment: Global___AlignmentCapability | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["alignment", b"alignment", "protocol", b"protocol"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alignment", b"alignment", "capabilities", b"capabilities", "engine_id", b"engine_id", "engine_version", b"engine_version", "max_concurrency", b"max_concurrency", "protocol", b"protocol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DescribeResponse: _TypeAlias = DescribeResponse  # noqa: Y015

@_typing.final
class AlignmentCapability(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNITS_FIELD_NUMBER: _builtins.int
    LANGUAGES_FIELD_NUMBER: _builtins.int
    ALIGNER_FIELD_NUMBER: _builtins.int
    aligner: _builtins.str
    @_builtins.property
    def units(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def languages(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        units: _abc.Iterable[_builtins.str] | None = ...,
        languages: _abc.Iterable[_builtins.str] | None = ...,
        aligner: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aligner", b"aligner", "languages", b"languages", "units", b"units"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlignmentCapability: _TypeAlias = AlignmentCapability  # noqa: Y015

@_typing.final
class HealthRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthRequest: _TypeAlias = HealthRequest  # noqa: Y015

@_typing.final
class HealthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HealthResponse._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_UNSPECIFIED: HealthResponse._Status.ValueType  # 0
        STARTING: HealthResponse._Status.ValueType  # 1
        READY: HealthResponse._Status.ValueType  # 2
        DEGRADED: HealthResponse._Status.ValueType  # 3

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_UNSPECIFIED: HealthResponse.Status.ValueType  # 0
    STARTING: HealthResponse.Status.ValueType  # 1
    READY: HealthResponse.Status.ValueType  # 2
    DEGRADED: HealthResponse.Status.ValueType  # 3

    STATUS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    status: Global___HealthResponse.Status.ValueType
    message: _builtins.str
    def __init__(
        self,
        *,
        status: Global___HealthResponse.Status.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthResponse: _TypeAlias = HealthResponse  # noqa: Y015

@_typing.final
class ModelVariant(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    label: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        label: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "label", b"label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelVariant: _TypeAlias = ModelVariant  # noqa: Y015

@_typing.final
class CompatibilityEvidence(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    message: _builtins.str
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CompatibilityEvidence: _TypeAlias = CompatibilityEvidence  # noqa: Y015

@_typing.final
class WorkerError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DetailsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    RETRYABLE_FIELD_NUMBER: _builtins.int
    DETAILS_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    message: _builtins.str
    retryable: _builtins.bool
    @_builtins.property
    def details(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        message: _builtins.str = ...,
        retryable: _builtins.bool = ...,
        details: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "details", b"details", "message", b"message", "retryable", b"retryable"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WorkerError: _TypeAlias = WorkerError  # noqa: Y015

@_typing.final
class ValidateModelRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REPOSITORY_ID_FIELD_NUMBER: _builtins.int
    REQUESTED_REVISION_FIELD_NUMBER: _builtins.int
    repository_id: _builtins.str
    requested_revision: _builtins.str
    def __init__(
        self,
        *,
        repository_id: _builtins.str = ...,
        requested_revision: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_requested_revision", b"_requested_revision", "requested_revision", b"requested_revision"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_requested_revision", b"_requested_revision", "repository_id", b"repository_id", "requested_revision", b"requested_revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__requested_revision: _TypeAlias = _typing.Literal["requested_revision"]  # noqa: Y015
    _WhichOneofArgType__requested_revision: _TypeAlias = _typing.Literal["_requested_revision", b"_requested_revision"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__requested_revision) -> _WhichOneofReturnType__requested_revision | None: ...

Global___ValidateModelRequest: _TypeAlias = ValidateModelRequest  # noqa: Y015

@_typing.final
class ValidateModelResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REPOSITORY_ID_FIELD_NUMBER: _builtins.int
    REQUESTED_REVISION_FIELD_NUMBER: _builtins.int
    RESOLVED_COMMIT_FIELD_NUMBER: _builtins.int
    COMPATIBLE_FIELD_NUMBER: _builtins.int
    ENGINE_ID_FIELD_NUMBER: _builtins.int
    ENGINE_VERSION_FIELD_NUMBER: _builtins.int
    REQUIRED_FILES_FIELD_NUMBER: _builtins.int
    AVAILABLE_VARIANTS_FIELD_NUMBER: _builtins.int
    ESTIMATED_BYTES_FIELD_NUMBER: _builtins.int
    EVIDENCE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    repository_id: _builtins.str
    requested_revision: _builtins.str
    resolved_commit: _builtins.str
    compatible: _builtins.bool
    engine_id: _builtins.str
    engine_version: _builtins.str
    estimated_bytes: _builtins.int
    @_builtins.property
    def required_files(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def available_variants(self) -> _containers.RepeatedCompositeFieldContainer[Global___ModelVariant]: ...
    @_builtins.property
    def evidence(self) -> _containers.RepeatedCompositeFieldContainer[Global___CompatibilityEvidence]: ...
    @_builtins.property
    def error(self) -> Global___WorkerError: ...
    def __init__(
        self,
        *,
        repository_id: _builtins.str = ...,
        requested_revision: _builtins.str | None = ...,
        resolved_commit: _builtins.str | None = ...,
        compatible: _builtins.bool = ...,
        engine_id: _builtins.str = ...,
        engine_version: _builtins.str = ...,
        required_files: _abc.Iterable[_builtins.str] | None = ...,
        available_variants: _abc.Iterable[Global___ModelVariant] | None = ...,
        estimated_bytes: _builtins.int | None = ...,
        evidence: _abc.Iterable[Global___CompatibilityEvidence] | None = ...,
        error: Global___WorkerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_estimated_bytes", b"_estimated_bytes", "_requested_revision", b"_requested_revision", "_resolved_commit", b"_resolved_commit", "error", b"error", "estimated_bytes", b"estimated_bytes", "requested_revision", b"requested_revision", "resolved_commit", b"resolved_commit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_estimated_bytes", b"_estimated_bytes", "_requested_revision", b"_requested_revision", "_resolved_commit", b"_resolved_commit", "available_variants", b"available_variants", "compatible", b"compatible", "engine_id", b"engine_id", "engine_version", b"engine_version", "error", b"error", "estimated_bytes", b"estimated_bytes", "evidence", b"evidence", "repository_id", b"repository_id", "requested_revision", b"requested_revision", "required_files", b"required_files", "resolved_commit", b"resolved_commit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__estimated_bytes: _TypeAlias = _typing.Literal["estimated_bytes"]  # noqa: Y015
    _WhichOneofArgType__estimated_bytes: _TypeAlias = _typing.Literal["_estimated_bytes", b"_estimated_bytes"]  # noqa: Y015
    _WhichOneofReturnType__requested_revision: _TypeAlias = _typing.Literal["requested_revision"]  # noqa: Y015
    _WhichOneofArgType__requested_revision: _TypeAlias = _typing.Literal["_requested_revision", b"_requested_revision"]  # noqa: Y015
    _WhichOneofReturnType__resolved_commit: _TypeAlias = _typing.Literal["resolved_commit"]  # noqa: Y015
    _WhichOneofArgType__resolved_commit: _TypeAlias = _typing.Literal["_resolved_commit", b"_resolved_commit"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__estimated_bytes) -> _WhichOneofReturnType__estimated_bytes | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__requested_revision) -> _WhichOneofReturnType__requested_revision | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__resolved_commit) -> _WhichOneofReturnType__resolved_commit | None: ...

Global___ValidateModelResponse: _TypeAlias = ValidateModelResponse  # noqa: Y015

@_typing.final
class DownloadModelRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REPOSITORY_ID_FIELD_NUMBER: _builtins.int
    RESOLVED_COMMIT_FIELD_NUMBER: _builtins.int
    VARIANT_FIELD_NUMBER: _builtins.int
    STAGING_DESTINATION_FIELD_NUMBER: _builtins.int
    repository_id: _builtins.str
    resolved_commit: _builtins.str
    variant: _builtins.str
    staging_destination: _builtins.str
    def __init__(
        self,
        *,
        repository_id: _builtins.str = ...,
        resolved_commit: _builtins.str = ...,
        variant: _builtins.str = ...,
        staging_destination: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["repository_id", b"repository_id", "resolved_commit", b"resolved_commit", "staging_destination", b"staging_destination", "variant", b"variant"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DownloadModelRequest: _TypeAlias = DownloadModelRequest  # noqa: Y015

@_typing.final
class ManifestFile(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELATIVE_PATH_FIELD_NUMBER: _builtins.int
    BYTE_SIZE_FIELD_NUMBER: _builtins.int
    SHA256_FIELD_NUMBER: _builtins.int
    relative_path: _builtins.str
    byte_size: _builtins.int
    sha256: _builtins.str
    def __init__(
        self,
        *,
        relative_path: _builtins.str = ...,
        byte_size: _builtins.int = ...,
        sha256: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["byte_size", b"byte_size", "relative_path", b"relative_path", "sha256", b"sha256"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ManifestFile: _TypeAlias = ManifestFile  # noqa: Y015

@_typing.final
class ModelManifest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REPOSITORY_ID_FIELD_NUMBER: _builtins.int
    RESOLVED_COMMIT_FIELD_NUMBER: _builtins.int
    VARIANT_FIELD_NUMBER: _builtins.int
    FILES_FIELD_NUMBER: _builtins.int
    BYTE_SIZE_FIELD_NUMBER: _builtins.int
    repository_id: _builtins.str
    resolved_commit: _builtins.str
    variant: _builtins.str
    byte_size: _builtins.int
    @_builtins.property
    def files(self) -> _containers.RepeatedCompositeFieldContainer[Global___ManifestFile]: ...
    def __init__(
        self,
        *,
        repository_id: _builtins.str = ...,
        resolved_commit: _builtins.str = ...,
        variant: _builtins.str = ...,
        files: _abc.Iterable[Global___ManifestFile] | None = ...,
        byte_size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["byte_size", b"byte_size", "files", b"files", "repository_id", b"repository_id", "resolved_commit", b"resolved_commit", "variant", b"variant"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelManifest: _TypeAlias = ModelManifest  # noqa: Y015

@_typing.final
class DownloadProgress(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: _builtins.int
    PHASE_FIELD_NUMBER: _builtins.int
    BYTES_DOWNLOADED_FIELD_NUMBER: _builtins.int
    TOTAL_BYTES_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    WARNINGS_FIELD_NUMBER: _builtins.int
    sequence: _builtins.int
    phase: Global___DownloadPhase.ValueType
    bytes_downloaded: _builtins.int
    total_bytes: _builtins.int
    message: _builtins.str
    @_builtins.property
    def warnings(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        sequence: _builtins.int = ...,
        phase: Global___DownloadPhase.ValueType = ...,
        bytes_downloaded: _builtins.int = ...,
        total_bytes: _builtins.int | None = ...,
        message: _builtins.str = ...,
        warnings: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_total_bytes", b"_total_bytes", "total_bytes", b"total_bytes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_total_bytes", b"_total_bytes", "bytes_downloaded", b"bytes_downloaded", "message", b"message", "phase", b"phase", "sequence", b"sequence", "total_bytes", b"total_bytes", "warnings", b"warnings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__total_bytes: _TypeAlias = _typing.Literal["total_bytes"]  # noqa: Y015
    _WhichOneofArgType__total_bytes: _TypeAlias = _typing.Literal["_total_bytes", b"_total_bytes"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__total_bytes) -> _WhichOneofReturnType__total_bytes | None: ...

Global___DownloadProgress: _TypeAlias = DownloadProgress  # noqa: Y015

@_typing.final
class DownloadModelEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROGRESS_FIELD_NUMBER: _builtins.int
    MANIFEST_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def progress(self) -> Global___DownloadProgress: ...
    @_builtins.property
    def manifest(self) -> Global___ModelManifest: ...
    @_builtins.property
    def error(self) -> Global___WorkerError: ...
    def __init__(
        self,
        *,
        progress: Global___DownloadProgress | None = ...,
        manifest: Global___ModelManifest | None = ...,
        error: Global___WorkerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "manifest", b"manifest", "payload", b"payload", "progress", b"progress"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "manifest", b"manifest", "payload", b"payload", "progress", b"progress"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["progress", "manifest", "error"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___DownloadModelEvent: _TypeAlias = DownloadModelEvent  # noqa: Y015

@_typing.final
class LoadModelRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    CACHE_PATH_FIELD_NUMBER: _builtins.int
    VARIANT_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    cache_path: _builtins.str
    variant: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        cache_path: _builtins.str = ...,
        variant: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cache_path", b"cache_path", "model_id", b"model_id", "variant", b"variant"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LoadModelRequest: _TypeAlias = LoadModelRequest  # noqa: Y015

@_typing.final
class LoadModelResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LOADED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    loaded: _builtins.bool
    @_builtins.property
    def error(self) -> Global___WorkerError: ...
    def __init__(
        self,
        *,
        loaded: _builtins.bool = ...,
        error: Global___WorkerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "loaded", b"loaded"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LoadModelResponse: _TypeAlias = LoadModelResponse  # noqa: Y015

@_typing.final
class UnloadModelRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model_id", b"model_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnloadModelRequest: _TypeAlias = UnloadModelRequest  # noqa: Y015

@_typing.final
class UnloadModelResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNLOADED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    unloaded: _builtins.bool
    @_builtins.property
    def error(self) -> Global___WorkerError: ...
    def __init__(
        self,
        *,
        unloaded: _builtins.bool = ...,
        error: Global___WorkerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "unloaded", b"unloaded"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnloadModelResponse: _TypeAlias = UnloadModelResponse  # noqa: Y015

@_typing.final
class ListVoicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model_id", b"model_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListVoicesRequest: _TypeAlias = ListVoicesRequest  # noqa: Y015

@_typing.final
class PresetVoice(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    CAPABILITIES_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    label: _builtins.str
    @_builtins.property
    def capabilities(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        label: _builtins.str = ...,
        capabilities: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities", "id", b"id", "label", b"label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PresetVoice: _TypeAlias = PresetVoice  # noqa: Y015

@_typing.final
class ListVoicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICES_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def voices(self) -> _containers.RepeatedCompositeFieldContainer[Global___PresetVoice]: ...
    @_builtins.property
    def error(self) -> Global___WorkerError: ...
    def __init__(
        self,
        *,
        voices: _abc.Iterable[Global___PresetVoice] | None = ...,
        error: Global___WorkerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "voices", b"voices"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListVoicesResponse: _TypeAlias = ListVoicesResponse  # noqa: Y015

@_typing.final
class ReferenceAudio(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REFERENCE_PATH_FIELD_NUMBER: _builtins.int
    TRANSCRIPT_FIELD_NUMBER: _builtins.int
    reference_path: _builtins.str
    """Core-owned path relative to the Worker's managed data root."""
    transcript: _builtins.str
    def __init__(
        self,
        *,
        reference_path: _builtins.str = ...,
        transcript: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_transcript", b"_transcript", "transcript", b"transcript"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_transcript", b"_transcript", "reference_path", b"reference_path", "transcript", b"transcript"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__transcript: _TypeAlias = _typing.Literal["transcript"]  # noqa: Y015
    _WhichOneofArgType__transcript: _TypeAlias = _typing.Literal["_transcript", b"_transcript"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__transcript) -> _WhichOneofReturnType__transcript | None: ...

Global___ReferenceAudio: _TypeAlias = ReferenceAudio  # noqa: Y015

@_typing.final
class ValidateReferenceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    REFERENCE_PATH_FIELD_NUMBER: _builtins.int
    TRANSCRIPT_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    reference_path: _builtins.str
    transcript: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        reference_path: _builtins.str = ...,
        transcript: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_transcript", b"_transcript", "transcript", b"transcript"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_transcript", b"_transcript", "model_id", b"model_id", "reference_path", b"reference_path", "transcript", b"transcript"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__transcript: _TypeAlias = _typing.Literal["transcript"]  # noqa: Y015
    _WhichOneofArgType__transcript: _TypeAlias = _typing.Literal["_transcript", b"_transcript"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__transcript) -> _WhichOneofReturnType__transcript | None: ...

Global___ValidateReferenceRequest: _TypeAlias = ValidateReferenceRequest  # noqa: Y015

@_typing.final
class ReferenceMetadata(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SAMPLE_RATE_HZ_FIELD_NUMBER: _builtins.int
    CHANNELS_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    BYTE_SIZE_FIELD_NUMBER: _builtins.int
    CONTAINER_FIELD_NUMBER: _builtins.int
    sample_rate_hz: _builtins.int
    channels: _builtins.int
    duration_ms: _builtins.int
    byte_size: _builtins.int
    container: _builtins.str
    def __init__(
        self,
        *,
        sample_rate_hz: _builtins.int = ...,
        channels: _builtins.int = ...,
        duration_ms: _builtins.int = ...,
        byte_size: _builtins.int = ...,
        container: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["byte_size", b"byte_size", "channels", b"channels", "container", b"container", "duration_ms", b"duration_ms", "sample_rate_hz", b"sample_rate_hz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReferenceMetadata: _TypeAlias = ReferenceMetadata  # noqa: Y015

@_typing.final
class ValidateReferenceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALID_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    EVIDENCE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    valid: _builtins.bool
    @_builtins.property
    def metadata(self) -> Global___ReferenceMetadata: ...
    @_builtins.property
    def evidence(self) -> _containers.RepeatedCompositeFieldContainer[Global___CompatibilityEvidence]: ...
    @_builtins.property
    def error(self) -> Global___WorkerError: ...
    def __init__(
        self,
        *,
        valid: _builtins.bool = ...,
        metadata: Global___ReferenceMetadata | None = ...,
        evidence: _abc.Iterable[Global___CompatibilityEvidence] | None = ...,
        error: Global___WorkerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "evidence", b"evidence", "metadata", b"metadata", "valid", b"valid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateReferenceResponse: _TypeAlias = ValidateReferenceResponse  # noqa: Y015

@_typing.final
class AlignmentUnit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    SOURCE_START_FIELD_NUMBER: _builtins.int
    SOURCE_END_FIELD_NUMBER: _builtins.int
    START_FRAMES_FIELD_NUMBER: _builtins.int
    END_FRAMES_FIELD_NUMBER: _builtins.int
    CONFIDENCE_FIELD_NUMBER: _builtins.int
    ESTIMATED_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    source_start: _builtins.int
    source_end: _builtins.int
    start_frames: _builtins.int
    end_frames: _builtins.int
    confidence: _builtins.float
    estimated: _builtins.bool
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        source_start: _builtins.int = ...,
        source_end: _builtins.int = ...,
        start_frames: _builtins.int = ...,
        end_frames: _builtins.int = ...,
        confidence: _builtins.float = ...,
        estimated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["confidence", b"confidence", "end_frames", b"end_frames", "estimated", b"estimated", "source_end", b"source_end", "source_start", b"source_start", "start_frames", b"start_frames", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlignmentUnit: _TypeAlias = AlignmentUnit  # noqa: Y015

@_typing.final
class AlignmentResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_VERSION_FIELD_NUMBER: _builtins.int
    TRANSCRIPT_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_HZ_FIELD_NUMBER: _builtins.int
    TOTAL_FRAMES_FIELD_NUMBER: _builtins.int
    UNIT_FIELD_NUMBER: _builtins.int
    ALIGNER_FIELD_NUMBER: _builtins.int
    UNITS_FIELD_NUMBER: _builtins.int
    schema_version: _builtins.int
    transcript: _builtins.str
    sample_rate_hz: _builtins.int
    total_frames: _builtins.int
    unit: _builtins.str
    aligner: _builtins.str
    @_builtins.property
    def units(self) -> _containers.RepeatedCompositeFieldContainer[Global___AlignmentUnit]: ...
    def __init__(
        self,
        *,
        schema_version: _builtins.int = ...,
        transcript: _builtins.str = ...,
        sample_rate_hz: _builtins.int = ...,
        total_frames: _builtins.int = ...,
        unit: _builtins.str = ...,
        aligner: _builtins.str = ...,
        units: _abc.Iterable[Global___AlignmentUnit] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aligner", b"aligner", "sample_rate_hz", b"sample_rate_hz", "schema_version", b"schema_version", "total_frames", b"total_frames", "transcript", b"transcript", "unit", b"unit", "units", b"units"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlignmentResult: _TypeAlias = AlignmentResult  # noqa: Y015

@_typing.final
class AlignRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    AUDIO_PATH_FIELD_NUMBER: _builtins.int
    TRANSCRIPT_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    audio_path: _builtins.str
    transcript: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        audio_path: _builtins.str = ...,
        transcript: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_path", b"audio_path", "model_id", b"model_id", "transcript", b"transcript"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlignRequest: _TypeAlias = AlignRequest  # noqa: Y015

@_typing.final
class AlignResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULT_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def result(self) -> Global___AlignmentResult: ...
    @_builtins.property
    def error(self) -> Global___WorkerError: ...
    def __init__(
        self,
        *,
        result: Global___AlignmentResult | None = ...,
        error: Global___WorkerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlignResponse: _TypeAlias = AlignResponse  # noqa: Y015

@_typing.final
class ProviderConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BASE_URL_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    API_KEY_FIELD_NUMBER: _builtins.int
    base_url: _builtins.str
    model: _builtins.str
    api_key: _builtins.str
    def __init__(
        self,
        *,
        base_url: _builtins.str = ...,
        model: _builtins.str = ...,
        api_key: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key", "base_url", b"base_url", "model", b"model"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProviderConfig: _TypeAlias = ProviderConfig  # noqa: Y015

@_typing.final
class SynthesisOptions(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPEED_FIELD_NUMBER: _builtins.int
    PITCH_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    speed: _builtins.float
    pitch: _builtins.float
    volume: _builtins.float
    def __init__(
        self,
        *,
        speed: _builtins.float | None = ...,
        pitch: _builtins.float | None = ...,
        volume: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_pitch", b"_pitch", "_speed", b"_speed", "_volume", b"_volume", "pitch", b"pitch", "speed", b"speed", "volume", b"volume"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_pitch", b"_pitch", "_speed", b"_speed", "_volume", b"_volume", "pitch", b"pitch", "speed", b"speed", "volume", b"volume"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__pitch: _TypeAlias = _typing.Literal["pitch"]  # noqa: Y015
    _WhichOneofArgType__pitch: _TypeAlias = _typing.Literal["_pitch", b"_pitch"]  # noqa: Y015
    _WhichOneofReturnType__speed: _TypeAlias = _typing.Literal["speed"]  # noqa: Y015
    _WhichOneofArgType__speed: _TypeAlias = _typing.Literal["_speed", b"_speed"]  # noqa: Y015
    _WhichOneofReturnType__volume: _TypeAlias = _typing.Literal["volume"]  # noqa: Y015
    _WhichOneofArgType__volume: _TypeAlias = _typing.Literal["_volume", b"_volume"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pitch) -> _WhichOneofReturnType__pitch | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__speed) -> _WhichOneofReturnType__speed | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__volume) -> _WhichOneofReturnType__volume | None: ...

Global___SynthesisOptions: _TypeAlias = SynthesisOptions  # noqa: Y015

@_typing.final
class SynthesizeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    VOICE_ID_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    PROVIDER_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    voice_id: _builtins.str
    text: _builtins.str
    @_builtins.property
    def reference(self) -> Global___ReferenceAudio: ...
    @_builtins.property
    def provider(self) -> Global___ProviderConfig: ...
    @_builtins.property
    def options(self) -> Global___SynthesisOptions: ...
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        voice_id: _builtins.str = ...,
        reference: Global___ReferenceAudio | None = ...,
        text: _builtins.str = ...,
        provider: Global___ProviderConfig | None = ...,
        options: Global___SynthesisOptions | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["options", b"options", "provider", b"provider", "reference", b"reference", "voice_id", b"voice_id", "voice_source", b"voice_source"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model_id", b"model_id", "options", b"options", "provider", b"provider", "reference", b"reference", "text", b"text", "voice_id", b"voice_id", "voice_source", b"voice_source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_voice_source: _TypeAlias = _typing.Literal["voice_id", "reference"]  # noqa: Y015
    _WhichOneofArgType_voice_source: _TypeAlias = _typing.Literal["voice_source", b"voice_source"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_voice_source) -> _WhichOneofReturnType_voice_source | None: ...

Global___SynthesizeRequest: _TypeAlias = SynthesizeRequest  # noqa: Y015

@_typing.final
class AudioHeader(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SAMPLE_RATE_HZ_FIELD_NUMBER: _builtins.int
    CHANNELS_FIELD_NUMBER: _builtins.int
    SAMPLE_FORMAT_FIELD_NUMBER: _builtins.int
    sample_rate_hz: _builtins.int
    channels: _builtins.int
    sample_format: Global___SampleFormat.ValueType
    def __init__(
        self,
        *,
        sample_rate_hz: _builtins.int = ...,
        channels: _builtins.int = ...,
        sample_format: Global___SampleFormat.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels", "sample_format", b"sample_format", "sample_rate_hz", b"sample_rate_hz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioHeader: _TypeAlias = AudioHeader  # noqa: Y015

@_typing.final
class PcmChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: _builtins.int
    PCM_FIELD_NUMBER: _builtins.int
    sequence: _builtins.int
    pcm: _builtins.bytes
    def __init__(
        self,
        *,
        sequence: _builtins.int = ...,
        pcm: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pcm", b"pcm", "sequence", b"sequence"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PcmChunk: _TypeAlias = PcmChunk  # noqa: Y015

@_typing.final
class SynthesisProgress(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    DURATION_FRAMES_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    duration_frames: _builtins.int
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
        duration_frames: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_frames", b"duration_frames", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SynthesisProgress: _TypeAlias = SynthesisProgress  # noqa: Y015

@_typing.final
class SynthesisResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOTAL_FRAMES_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    total_frames: _builtins.int
    duration_ms: _builtins.int
    def __init__(
        self,
        *,
        total_frames: _builtins.int = ...,
        duration_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_ms", b"duration_ms", "total_frames", b"total_frames"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SynthesisResult: _TypeAlias = SynthesisResult  # noqa: Y015

@_typing.final
class SynthesisEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    CHUNK_FIELD_NUMBER: _builtins.int
    PROGRESS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def header(self) -> Global___AudioHeader: ...
    @_builtins.property
    def chunk(self) -> Global___PcmChunk: ...
    @_builtins.property
    def progress(self) -> Global___SynthesisProgress: ...
    @_builtins.property
    def result(self) -> Global___SynthesisResult: ...
    @_builtins.property
    def error(self) -> Global___WorkerError: ...
    def __init__(
        self,
        *,
        header: Global___AudioHeader | None = ...,
        chunk: Global___PcmChunk | None = ...,
        progress: Global___SynthesisProgress | None = ...,
        result: Global___SynthesisResult | None = ...,
        error: Global___WorkerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "error", b"error", "header", b"header", "payload", b"payload", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "error", b"error", "header", b"header", "payload", b"payload", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["header", "chunk", "progress", "result", "error"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___SynthesisEvent: _TypeAlias = SynthesisEvent  # noqa: Y015
