"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from . import engine_pb2 as _engine_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EngineWorkerStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EngineWorkerAsyncStub: ...
    Describe: _grpc.UnaryUnaryMultiCallable[_engine_pb2.DescribeRequest, _engine_pb2.DescribeResponse]
    Health: _grpc.UnaryUnaryMultiCallable[_engine_pb2.HealthRequest, _engine_pb2.HealthResponse]
    ValidateModel: _grpc.UnaryUnaryMultiCallable[_engine_pb2.ValidateModelRequest, _engine_pb2.ValidateModelResponse]
    ValidateReference: _grpc.UnaryUnaryMultiCallable[_engine_pb2.ValidateReferenceRequest, _engine_pb2.ValidateReferenceResponse]
    DownloadModel: _grpc.UnaryStreamMultiCallable[_engine_pb2.DownloadModelRequest, _engine_pb2.DownloadModelEvent]
    LoadModel: _grpc.UnaryUnaryMultiCallable[_engine_pb2.LoadModelRequest, _engine_pb2.LoadModelResponse]
    UnloadModel: _grpc.UnaryUnaryMultiCallable[_engine_pb2.UnloadModelRequest, _engine_pb2.UnloadModelResponse]
    ListVoices: _grpc.UnaryUnaryMultiCallable[_engine_pb2.ListVoicesRequest, _engine_pb2.ListVoicesResponse]
    Align: _grpc.UnaryUnaryMultiCallable[_engine_pb2.AlignRequest, _engine_pb2.AlignResponse]
    Synthesize: _grpc.UnaryStreamMultiCallable[_engine_pb2.SynthesizeRequest, _engine_pb2.SynthesisEvent]

@_typing.type_check_only
class EngineWorkerAsyncStub(EngineWorkerStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Describe: _aio.UnaryUnaryMultiCallable[_engine_pb2.DescribeRequest, _engine_pb2.DescribeResponse]  # type: ignore[assignment]
    Health: _aio.UnaryUnaryMultiCallable[_engine_pb2.HealthRequest, _engine_pb2.HealthResponse]  # type: ignore[assignment]
    ValidateModel: _aio.UnaryUnaryMultiCallable[_engine_pb2.ValidateModelRequest, _engine_pb2.ValidateModelResponse]  # type: ignore[assignment]
    ValidateReference: _aio.UnaryUnaryMultiCallable[_engine_pb2.ValidateReferenceRequest, _engine_pb2.ValidateReferenceResponse]  # type: ignore[assignment]
    DownloadModel: _aio.UnaryStreamMultiCallable[_engine_pb2.DownloadModelRequest, _engine_pb2.DownloadModelEvent]  # type: ignore[assignment]
    LoadModel: _aio.UnaryUnaryMultiCallable[_engine_pb2.LoadModelRequest, _engine_pb2.LoadModelResponse]  # type: ignore[assignment]
    UnloadModel: _aio.UnaryUnaryMultiCallable[_engine_pb2.UnloadModelRequest, _engine_pb2.UnloadModelResponse]  # type: ignore[assignment]
    ListVoices: _aio.UnaryUnaryMultiCallable[_engine_pb2.ListVoicesRequest, _engine_pb2.ListVoicesResponse]  # type: ignore[assignment]
    Align: _aio.UnaryUnaryMultiCallable[_engine_pb2.AlignRequest, _engine_pb2.AlignResponse]  # type: ignore[assignment]
    Synthesize: _aio.UnaryStreamMultiCallable[_engine_pb2.SynthesizeRequest, _engine_pb2.SynthesisEvent]  # type: ignore[assignment]

class EngineWorkerServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Describe(
        self,
        request: _engine_pb2.DescribeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.DescribeResponse, _abc.Awaitable[_engine_pb2.DescribeResponse]]: ...

    @_abc_1.abstractmethod
    def Health(
        self,
        request: _engine_pb2.HealthRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.HealthResponse, _abc.Awaitable[_engine_pb2.HealthResponse]]: ...

    @_abc_1.abstractmethod
    def ValidateModel(
        self,
        request: _engine_pb2.ValidateModelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.ValidateModelResponse, _abc.Awaitable[_engine_pb2.ValidateModelResponse]]: ...

    @_abc_1.abstractmethod
    def ValidateReference(
        self,
        request: _engine_pb2.ValidateReferenceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.ValidateReferenceResponse, _abc.Awaitable[_engine_pb2.ValidateReferenceResponse]]: ...

    @_abc_1.abstractmethod
    def DownloadModel(
        self,
        request: _engine_pb2.DownloadModelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_engine_pb2.DownloadModelEvent], _abc.AsyncIterator[_engine_pb2.DownloadModelEvent]]: ...

    @_abc_1.abstractmethod
    def LoadModel(
        self,
        request: _engine_pb2.LoadModelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.LoadModelResponse, _abc.Awaitable[_engine_pb2.LoadModelResponse]]: ...

    @_abc_1.abstractmethod
    def UnloadModel(
        self,
        request: _engine_pb2.UnloadModelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.UnloadModelResponse, _abc.Awaitable[_engine_pb2.UnloadModelResponse]]: ...

    @_abc_1.abstractmethod
    def ListVoices(
        self,
        request: _engine_pb2.ListVoicesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.ListVoicesResponse, _abc.Awaitable[_engine_pb2.ListVoicesResponse]]: ...

    @_abc_1.abstractmethod
    def Align(
        self,
        request: _engine_pb2.AlignRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_engine_pb2.AlignResponse, _abc.Awaitable[_engine_pb2.AlignResponse]]: ...

    @_abc_1.abstractmethod
    def Synthesize(
        self,
        request: _engine_pb2.SynthesizeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_engine_pb2.SynthesisEvent], _abc.AsyncIterator[_engine_pb2.SynthesisEvent]]: ...

def add_EngineWorkerServicer_to_server(servicer: EngineWorkerServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
