# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import engine_pb2 as engine_dot_v1_dot_engine__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine/v1/engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineWorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/tts_studio.engine.v1.EngineWorker/Describe',
                request_serializer=engine_dot_v1_dot_engine__pb2.DescribeRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.DescribeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/tts_studio.engine.v1.EngineWorker/Health',
                request_serializer=engine_dot_v1_dot_engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ValidateModel = channel.unary_unary(
                '/tts_studio.engine.v1.EngineWorker/ValidateModel',
                request_serializer=engine_dot_v1_dot_engine__pb2.ValidateModelRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.ValidateModelResponse.FromString,
                _registered_method=True)
        self.ValidateReference = channel.unary_unary(
                '/tts_studio.engine.v1.EngineWorker/ValidateReference',
                request_serializer=engine_dot_v1_dot_engine__pb2.ValidateReferenceRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.ValidateReferenceResponse.FromString,
                _registered_method=True)
        self.DownloadModel = channel.unary_stream(
                '/tts_studio.engine.v1.EngineWorker/DownloadModel',
                request_serializer=engine_dot_v1_dot_engine__pb2.DownloadModelRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.DownloadModelEvent.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/tts_studio.engine.v1.EngineWorker/LoadModel',
                request_serializer=engine_dot_v1_dot_engine__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/tts_studio.engine.v1.EngineWorker/UnloadModel',
                request_serializer=engine_dot_v1_dot_engine__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.ListVoices = channel.unary_unary(
                '/tts_studio.engine.v1.EngineWorker/ListVoices',
                request_serializer=engine_dot_v1_dot_engine__pb2.ListVoicesRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.ListVoicesResponse.FromString,
                _registered_method=True)
        self.Align = channel.unary_unary(
                '/tts_studio.engine.v1.EngineWorker/Align',
                request_serializer=engine_dot_v1_dot_engine__pb2.AlignRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.AlignResponse.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_stream(
                '/tts_studio.engine.v1.EngineWorker/Synthesize',
                request_serializer=engine_dot_v1_dot_engine__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.SynthesisEvent.FromString,
                _registered_method=True)


class EngineWorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateReference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Align(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.DescribeRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.DescribeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.HealthRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.HealthResponse.SerializeToString,
            ),
            'ValidateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateModel,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.ValidateModelRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.ValidateModelResponse.SerializeToString,
            ),
            'ValidateReference': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateReference,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.ValidateReferenceRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.ValidateReferenceResponse.SerializeToString,
            ),
            'DownloadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.DownloadModelRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.DownloadModelEvent.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.LoadModelRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.UnloadModelRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.UnloadModelResponse.SerializeToString,
            ),
            'ListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVoices,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.ListVoicesRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.ListVoicesResponse.SerializeToString,
            ),
            'Align': grpc.unary_unary_rpc_method_handler(
                    servicer.Align,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.AlignRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.AlignResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.SynthesizeRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.SynthesisEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts_studio.engine.v1.EngineWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts_studio.engine.v1.EngineWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineWorker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/Describe',
            engine_dot_v1_dot_engine__pb2.DescribeRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/Health',
            engine_dot_v1_dot_engine__pb2.HealthRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/ValidateModel',
            engine_dot_v1_dot_engine__pb2.ValidateModelRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.ValidateModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/ValidateReference',
            engine_dot_v1_dot_engine__pb2.ValidateReferenceRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.ValidateReferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/DownloadModel',
            engine_dot_v1_dot_engine__pb2.DownloadModelRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.DownloadModelEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/LoadModel',
            engine_dot_v1_dot_engine__pb2.LoadModelRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/UnloadModel',
            engine_dot_v1_dot_engine__pb2.UnloadModelRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/ListVoices',
            engine_dot_v1_dot_engine__pb2.ListVoicesRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.ListVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Align(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/Align',
            engine_dot_v1_dot_engine__pb2.AlignRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.AlignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts_studio.engine.v1.EngineWorker/Synthesize',
            engine_dot_v1_dot_engine__pb2.SynthesizeRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.SynthesisEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
