"""Generate deterministic TypeScript and Python types from the Core OpenAPI schema."""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any, cast

from tts_studio.config import Settings
from tts_studio.server.app import create_app


def _schema_type(schema: dict[str, Any], indent: int = 0) -> str:
    if schema.get("format") == "binary":
        return "Blob"
    if "$ref" in schema:
        return cast(str, schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(_schema_type(item, indent) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_schema_type(item, indent) for item in schema["oneOf"])
    if "allOf" in schema:
        return " & ".join(_schema_type(item, indent) for item in schema["allOf"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if schema.get("type") == "array":
        return f"Array<{_schema_type(schema.get('items', {}), indent)}>"
    if schema.get("type") == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if not properties:
            return "Record<string, unknown>"
        spaces = " " * (indent + 2)
        lines = ["{\n"]
        required = set(schema.get("required", []))
        for name in sorted(properties):
            optional = "" if name in required else "?"
            lines.append(
                f"{spaces}{name}{optional}: {_schema_type(properties[name], indent + 2)};\n"
            )
        lines.append(" " * indent + "}")
        return "".join(lines)
    schema_type = schema.get("type")
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(schema_type if isinstance(schema_type, str) else "", "unknown")


def _response_schema(content: dict[str, Any]) -> dict[str, Any]:
    schemas = [item.get("schema", {}) for item in content.values() if isinstance(item, dict)]
    if len(schemas) == 1:
        return schemas[0]
    return {"oneOf": schemas}


def render_schema(schema: dict[str, Any]) -> str:
    """Render the current FastAPI schema as stable TypeScript declarations."""
    components = schema.get("components", {}).get("schemas", {})
    lines = [
        "// This file is generated by scripts/generate_openapi_client.py. Do not edit.",
        "// Source: FastAPI app.openapi(); renderer format: tts-studio-openapi-v1.",
        "",
    ]
    for name in sorted(components):
        lines.extend([f"export type {name} = {_schema_type(components[name])};", ""])
    paths = schema.get("paths", {})
    lines.append("export type ApiPaths = {")
    for path in sorted(paths):
        lines.append(f"  {json.dumps(path)}: {{")
        for method in sorted(paths[path]):
            operation = paths[path][method]
            if not isinstance(operation, dict):
                continue
            response: Any = operation.get("responses", {}).get("200") or next(
                iter(operation.get("responses", {}).values()), {}
            )
            content = response.get("content", {}) if isinstance(response, dict) else {}
            response_schema = _response_schema(content) if content else {}
            lines.append(f"    {method}: {{ response: {_schema_type(response_schema)} }};")
        lines.append("  };")
    lines.extend(["};", ""])
    return "\n".join(lines)


def _python_schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return cast(str, schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(_python_schema_type(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_python_schema_type(item) for item in schema["oneOf"])
    if "allOf" in schema:
        items = schema["allOf"]
        return _python_schema_type(items[0]) if len(items) == 1 else "Any"
    if "const" in schema:
        value = schema["const"]
        rendered = json.dumps(value) if isinstance(value, str) else repr(value)
        return f"Literal[{rendered}]"
    if "enum" in schema:
        values = [
            json.dumps(value) if isinstance(value, str) else repr(value) for value in schema["enum"]
        ]
        return f"Literal[{', '.join(values)}]"
    if schema.get("type") == "array":
        return f"list[{_python_schema_type(schema.get('items', {}))}]"
    if schema.get("type") == "object" or "properties" in schema:
        return "dict[str, Any]"
    schema_type = schema.get("type")
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "null": "None",
    }.get(schema_type if isinstance(schema_type, str) else "", "Any")


def _python_field(name: str, schema: dict[str, Any], *, required: bool) -> str:
    annotation = _python_schema_type(schema)
    if required:
        return f"    {name}: {annotation}"
    if "None" not in annotation.split(" | "):
        annotation = f"{annotation} | None"
    return f"    {name}: {annotation} = None"


def render_python_schema(schema: dict[str, Any]) -> str:
    """Render the current FastAPI schema as importable Pydantic response types."""
    components = schema.get("components", {}).get("schemas", {})
    lines = [
        '"""Generated public API types. Do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel",
        "",
        "",
    ]
    model_names: list[str] = []
    for name in sorted(components):
        component = components[name]
        properties = component.get("properties", {})
        if component.get("type") != "object" and not properties:
            continue
        model_names.append(name)
        lines.append(f"class {name}(BaseModel):")
        required = set(component.get("required", []))
        if not properties:
            lines.append("    pass")
        else:
            for property_name in sorted(properties):
                lines.append(
                    _python_field(
                        property_name,
                        properties[property_name],
                        required=property_name in required,
                    )
                )
        lines.extend(["", ""])

    if model_names:
        lines.append("for _model in (")
        lines.extend(f"    {name}," for name in model_names)
        lines.extend(["):", "    _model.model_rebuild()", "", "del _model", ""])
    return "\n".join(lines)


def generate(output_path: Path, python_output_path: Path | None = None) -> str:
    """Generate and write clients, returning the TypeScript contents."""
    with tempfile.TemporaryDirectory(prefix="tts-studio-openapi-") as data_dir:
        app = create_app(Settings.resolve(Path(data_dir)))
        schema = app.openapi()
        contents = render_schema(schema)
        python_contents = render_python_schema(schema)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(contents, encoding="utf-8", newline="\n")
    if python_output_path is not None:
        python_output_path.parent.mkdir(parents=True, exist_ok=True)
        python_output_path.write_text(python_contents, encoding="utf-8", newline="\n")
    return contents


def main() -> int:
    repository_root = Path(__file__).resolve().parents[1]
    generate(
        repository_root / "web" / "src" / "generated" / "api.ts",
        repository_root / "src" / "tts_studio" / "generated" / "api.py",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
